#!/usr/bin/env python3
"""Pack a Neko.app character folder back into an oneko.js sprite sheet.

The inverse of sheet2char.py: it reads a *.nekochar folder and writes the
256x128 PNG (8x4 grid of 32x32 cells) that oneko.js and its ports expect, so a
character imported into the macOS app can be handed to the web version.

    python3 tools/char2sheet.py CHARACTER.nekochar OUT.png
    python3 tools/char2sheet.py --all Resources/Characters OUTPUT_DIR

--verify SHEET compares the packed result against an existing sheet instead of
writing anything, which is how the round trip is kept honest.
"""

import argparse
import os
import plistlib
import sys

from PIL import Image

from sheet2char import CELL, CELLS, HEIGHT, WIDTH


def frame_files(folder):
    """base frame name -> file name, taken from the manifest."""
    manifest = plistlib.load(open(os.path.join(folder, "character.plist"), "rb"))
    files = {}
    for state in manifest["States"].values():
        for name in state["Frames"]:
            files[os.path.splitext(name)[0]] = name
    return manifest, files


def pack(folder):
    manifest, files = frame_files(folder)
    side = (manifest.get("SpriteWidth"), manifest.get("SpriteHeight"))
    if side != (CELL, CELL):
        print("%s: %sx%s sprites scaled down to %dpx for the sheet"
              % (folder, side[0], side[1], CELL))
    sheet = Image.new("RGBA", (WIDTH, HEIGHT), (0, 0, 0, 0))
    missing = []
    for (col, row), frame in CELLS.items():
        name = files.get(frame)
        if name is None:
            missing.append(frame)
            continue
        cell = Image.open(os.path.join(folder, name)).convert("RGBA")
        # A character drawn larger than a cell, which only the desktop app can
        # use at full size, is scaled down rather than left out of the sheet.
        if cell.size != (CELL, CELL):
            cell = cell.resize((CELL, CELL), Image.BOX)
        sheet.paste(cell, (col * CELL, row * CELL))
    if missing:
        print("%s: no frame for %s" % (folder, ", ".join(sorted(missing))))
    return manifest, sheet


def differing_pixels(a, b):
    ap, bp = a.load(), b.load()
    return sum(1 for y in range(a.height) for x in range(a.width)
               if ap[x, y][3] != bp[x, y][3]
               or (ap[x, y][3] and ap[x, y][:3] != bp[x, y][:3]))


def ts_string(value):
    return '"%s"' % str(value or "").replace("\\", "\\\\").replace('"', '\\"')


def write_registry(path, manifests):
    """Emit the TypeScript registry, so it cannot drift from the manifests."""
    lines = [
        "// Generated by tools/char2sheet.py --registry. Do not edit by hand:",
        "// it mirrors the character.plist manifests in Resources/Characters.",
        "",
        "export interface OnekoCharacter {",
        "  /** Matches the Identifier in the macOS app's character.plist. */",
        "  readonly id: OnekoCharacterId;",
        "  /** Name to show in a picker. */",
        "  readonly name: string;",
        "  /** File name of the sprite sheet inside the assets folder. */",
        "  readonly sheet: string;",
        "  /** Where the sprites came from, empty when unrecorded. */",
        "  readonly author: string;",
        "  /** Licence note carried over from the manifest, empty when unrecorded. */",
        "  readonly licence: string;",
        "}",
        "",
        "export const ONEKO_CHARACTER_IDS = [",
    ]
    for m in manifests:
        lines.append("  %s," % ts_string(m["Identifier"]))
    lines += [
        "] as const;",
        "",
        "export type OnekoCharacterId = (typeof ONEKO_CHARACTER_IDS)[number];",
        "",
        "export const ONEKO_CHARACTERS: readonly OnekoCharacter[] = [",
    ]
    for m in manifests:
        lines += [
            "  {",
            "    id: %s," % ts_string(m["Identifier"]),
            "    name: %s," % ts_string(m["Name"]),
            "    sheet: %s," % ts_string(m["Identifier"] + ".png"),
            "    author: %s," % ts_string(m.get("Author")),
            "    licence: %s," % ts_string(m.get("License")),
            "  },",
        ]
    lines += [
        "];",
        "",
        "export const ONEKO_CHARACTERS_BY_ID: Readonly<Record<OnekoCharacterId, OnekoCharacter>> =",
        "  Object.fromEntries(ONEKO_CHARACTERS.map((character) => [character.id, character])) as Readonly<",
        "    Record<OnekoCharacterId, OnekoCharacter>",
        "  >;",
        "",
        "export const ONEKO_DEFAULT_CHARACTER_ID: OnekoCharacterId = %s;" % ts_string(
            "neko" if any(m["Identifier"] == "neko" for m in manifests) else manifests[0]["Identifier"]),
        "",
    ]
    with open(path, "w") as fh:
        fh.write("\n".join(lines))


def main():
    p = argparse.ArgumentParser()
    p.add_argument("source", help="a *.nekochar folder, or the folder holding them with --all")
    p.add_argument("out", help="output PNG, or output directory with --all")
    p.add_argument("--all", action="store_true", help="pack every character found")
    p.add_argument("--registry", metavar="FILE",
                   help="with --all, also write the TypeScript character registry")
    p.add_argument("--verify", metavar="SHEET", help="compare against an existing sheet")
    args = p.parse_args()

    if args.verify:
        _, sheet = pack(args.source)
        reference = Image.open(args.verify).convert("RGBA")
        if reference.size != (WIDTH, HEIGHT):
            padded = Image.new("RGBA", (WIDTH, HEIGHT), (0, 0, 0, 0))
            padded.paste(reference, (0, 0))
            reference = padded
        bad = differing_pixels(sheet, reference)
        print("%s vs %s: %d differing pixels" % (args.source, args.verify, bad))
        return 1 if bad else 0

    if not args.all:
        _, sheet = pack(args.source)
        sheet.save(args.out)
        print("wrote %s" % args.out)
        return 0

    os.makedirs(args.out, exist_ok=True)
    packed = []
    for entry in sorted(os.listdir(args.source), key=str.lower):
        if not entry.endswith(".nekochar"):
            continue
        manifest, sheet = pack(os.path.join(args.source, entry))
        path = os.path.join(args.out, manifest["Identifier"] + ".png")
        sheet.save(path)
        packed.append(manifest)
        print("wrote %s (%s)" % (path, manifest["Name"]))

    if args.registry:
        write_registry(args.registry, packed)
        print("wrote %s (%d characters)" % (args.registry, len(packed)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
