// Generated by tools/char2sheet.py --registry. Do not edit by hand:
// it mirrors the character.plist manifests in Resources/Characters.

export interface OnekoCharacter {
  /** Matches the Identifier in the macOS app's character.plist. */
  readonly id: OnekoCharacterId;
  /** Name to show in a picker. */
  readonly name: string;
  /** File name of the sprite sheet inside the assets folder. */
  readonly sheet: string;
  /** Where the sprites came from, empty when unrecorded. */
  readonly author: string;
  /** Licence note carried over from the manifest, empty when unrecorded. */
  readonly licence: string;
}

export const ONEKO_CHARACTER_IDS = [
  "ace",
  "alien",
  "black",
  "bunny",
  "calico",
  "dog",
  "eevee",
  "esmeralda",
  "fox",
  "ghost",
  "gray",
  "jess",
  "kina",
  "kuro",
  "lucy",
  "maia",
  "maria",
  "merlin-xl",
  "merlin",
  "mike",
  "moka",
  "neko",
  "owl-xl",
  "owl",
  "pinup",
  "sakura",
  "silver",
  "silversky",
  "snuupy",
  "spirit",
  "tomoyo",
  "tora",
  "valentine",
  "vaporwave",
] as const;

export type OnekoCharacterId = (typeof ONEKO_CHARACTER_IDS)[number];

export const ONEKO_CHARACTERS: readonly OnekoCharacter[] = [
  {
    id: "ace",
    name: "Ace",
    sheet: "ace.png",
    author: "onekocord skin collection",
    licence: "fan-made oneko.js skin, collection states no licence; check before redistributing",
  },
  {
    id: "alien",
    name: "Alien",
    sheet: "alien.png",
    author: "generated pixel art",
    licence: "generated pixel art, check before redistributing",
  },
  {
    id: "black",
    name: "Black",
    sheet: "black.png",
    author: "onekocord skin collection",
    licence: "fan-made oneko.js skin, collection states no licence; check before redistributing",
  },
  {
    id: "bunny",
    name: "Bunny",
    sheet: "bunny.png",
    author: "onekocord skin collection",
    licence: "fan-made oneko.js skin, collection states no licence; check before redistributing",
  },
  {
    id: "calico",
    name: "Calico",
    sheet: "calico.png",
    author: "onekocord skin collection",
    licence: "fan-made oneko.js skin, collection states no licence; check before redistributing",
  },
  {
    id: "dog",
    name: "Dog",
    sheet: "dog.png",
    author: "Masayuki Koba, Tatsuya Kato (oneko)",
    licence: "Public domain (oneko)",
  },
  {
    id: "eevee",
    name: "Eevee",
    sheet: "eevee.png",
    author: "onekocord skin collection",
    licence: "fan-made oneko.js skin, collection states no licence; check before redistributing",
  },
  {
    id: "esmeralda",
    name: "Esmeralda",
    sheet: "esmeralda.png",
    author: "onekocord skin collection",
    licence: "fan-made oneko.js skin, collection states no licence; check before redistributing",
  },
  {
    id: "fox",
    name: "Fox",
    sheet: "fox.png",
    author: "onekocord skin collection",
    licence: "fan-made oneko.js skin, collection states no licence; check before redistributing",
  },
  {
    id: "ghost",
    name: "Ghost",
    sheet: "ghost.png",
    author: "onekocord skin collection",
    licence: "fan-made oneko.js skin, collection states no licence; check before redistributing",
  },
  {
    id: "gray",
    name: "Gray",
    sheet: "gray.png",
    author: "onekocord skin collection",
    licence: "fan-made oneko.js skin, collection states no licence; check before redistributing",
  },
  {
    id: "jess",
    name: "Jess",
    sheet: "jess.png",
    author: "onekocord skin collection",
    licence: "fan-made oneko.js skin, collection states no licence; check before redistributing",
  },
  {
    id: "kina",
    name: "Kina",
    sheet: "kina.png",
    author: "onekocord skin collection",
    licence: "fan-made oneko.js skin, collection states no licence; check before redistributing",
  },
  {
    id: "kuro",
    name: "Kuro",
    sheet: "kuro.png",
    author: "inverted recolour of the oneko sprites",
    licence: "Public domain",
  },
  {
    id: "lucy",
    name: "Lucy",
    sheet: "lucy.png",
    author: "onekocord skin collection",
    licence: "fan-made oneko.js skin, collection states no licence; check before redistributing",
  },
  {
    id: "maia",
    name: "Maia",
    sheet: "maia.png",
    author: "onekocord skin collection",
    licence: "fan-made oneko.js skin, collection states no licence; check before redistributing",
  },
  {
    id: "maria",
    name: "Maria",
    sheet: "maria.png",
    author: "onekocord skin collection",
    licence: "fan-made oneko.js skin, collection states no licence; check before redistributing",
  },
  {
    id: "merlin-xl",
    name: "Merlin XL",
    sheet: "merlin-xl.png",
    author: "generated pixel art",
    licence: "generated pixel art, check before redistributing",
  },
  {
    id: "merlin",
    name: "Merlin",
    sheet: "merlin.png",
    author: "generated pixel art",
    licence: "generated pixel art, check before redistributing",
  },
  {
    id: "mike",
    name: "Mike",
    sheet: "mike.png",
    author: "onekocord skin collection",
    licence: "fan-made oneko.js skin, collection states no licence; check before redistributing",
  },
  {
    id: "moka",
    name: "Moka",
    sheet: "moka.png",
    author: "MCHAMSTERYT2/onekocord skin collection",
    licence: "fan-made oneko.js skin, collection states no licence; check before redistributing",
  },
  {
    id: "neko",
    name: "Neko",
    sheet: "neko.png",
    author: "Masayuki Koba (oneko)",
    licence: "Public domain",
  },
  {
    id: "owl-xl",
    name: "Owl XL",
    sheet: "owl-xl.png",
    author: "generated pixel art",
    licence: "generated pixel art, check before redistributing",
  },
  {
    id: "owl",
    name: "Owl",
    sheet: "owl.png",
    author: "generated pixel art",
    licence: "generated pixel art, check before redistributing",
  },
  {
    id: "pinup",
    name: "Pinup",
    sheet: "pinup.png",
    author: "generated pixel art",
    licence: "generated pixel art, check before redistributing",
  },
  {
    id: "sakura",
    name: "Sakura",
    sheet: "sakura.png",
    author: "Masayuki Koba, Tatsuya Kato (oneko)",
    licence: "oneko sprites; the artwork derives from Card Captor Sakura, check before redistributing",
  },
  {
    id: "silver",
    name: "Silver",
    sheet: "silver.png",
    author: "onekocord skin collection",
    licence: "fan-made oneko.js skin, collection states no licence; check before redistributing",
  },
  {
    id: "silversky",
    name: "Silversky",
    sheet: "silversky.png",
    author: "onekocord skin collection",
    licence: "fan-made oneko.js skin, collection states no licence; check before redistributing",
  },
  {
    id: "snuupy",
    name: "Snuupy",
    sheet: "snuupy.png",
    author: "onekocord skin collection",
    licence: "fan-made oneko.js skin, collection states no licence; check before redistributing",
  },
  {
    id: "spirit",
    name: "Spirit",
    sheet: "spirit.png",
    author: "onekocord skin collection",
    licence: "fan-made oneko.js skin, collection states no licence; check before redistributing",
  },
  {
    id: "tomoyo",
    name: "Tomoyo",
    sheet: "tomoyo.png",
    author: "Masayuki Koba, Tatsuya Kato (oneko)",
    licence: "oneko sprites; the artwork derives from Card Captor Sakura, check before redistributing",
  },
  {
    id: "tora",
    name: "Tora",
    sheet: "tora.png",
    author: "Masayuki Koba, Tatsuya Kato (oneko)",
    licence: "Public domain (oneko)",
  },
  {
    id: "valentine",
    name: "Valentine",
    sheet: "valentine.png",
    author: "onekocord skin collection",
    licence: "fan-made oneko.js skin, collection states no licence; check before redistributing",
  },
  {
    id: "vaporwave",
    name: "Vaporwave",
    sheet: "vaporwave.png",
    author: "kyrie25/spicetify-oneko",
    licence: "fan-made oneko.js skin, collection states no licence; check before redistributing",
  },
];

export const ONEKO_CHARACTERS_BY_ID: Readonly<Record<OnekoCharacterId, OnekoCharacter>> =
  Object.fromEntries(ONEKO_CHARACTERS.map((character) => [character.id, character])) as Readonly<
    Record<OnekoCharacterId, OnekoCharacter>
  >;

export const ONEKO_DEFAULT_CHARACTER_ID: OnekoCharacterId = "neko";
